### PR TITLE
Update: Improve readme file description

### PR DESCRIPTION
**Pull request by blessedjasonmwanza**
## Update: Improve readme file description
In this feature UI and UX update;
- setup GitHub flow
- setup linters 
- setup webpack
- Use ES6 modular code to build a complete 'Todo List web application'  inspired by the [Minimalist app](https://web.archive.org/web/20180320194056/http://www.getminimalist.com:80/)
- Deploy [Web application](https://blessedjasonmwanza.github.io/todo-list-copy/) using [GitHub web pages](https://pages.github.com/)

### CODE REVIEW

**Comment by ShoiraTa** [comment]
Hi @blessedjasonmwanza
Nice work on this project, have done a splendid job !
### Good Points:
- Project is set up correctly
- App is running as intended
- Good ReadMe
- No linter errors
- Your variables are descriptive, you have comments in main.js file which makes your code easy to understand and maintain
###  Optional suggestions: 

- It will be a good practice to favor the use of array methods such as `concat` over `push`, which doesn't mutate the array.
- You can use forEach function rather than for loop

**Comment by blessedjasonmwanza** [comment]
> Hi @blessedjasonmwanza Nice work on this project, have done a splendid job !
> 
> ### Good Points:
> * Project is set up correctly
> * App is running as intended
> * Good ReadMe
> * No linter errors
> * Your variables are descriptive, you have comments in main.js file which makes your code easy to understand and maintain
> 
> ### Optional suggestions:
> * It will be a good practice to favor the use of array methods such as `concat` over `push`, which doesn't mutate the array.
> * You can use forEach function rather than for loop

Hello @ShoiraTa , 

Thank you a lot for this insightful review. I am on to applying the suggested changes and will merge post-completion. 

> HappyCoding 🤓

**Comment by blessedjasonmwanza** [comment]
Hello @ShoiraTa,

Thanks a lot once more for that review. I have now [patched](https://github.com/blessedjasonmwanza/todo-list-copy/pull/1/commits/fde21a37c7e49b56d372963141141f6c0c91b907) the suggested changes.

**Comment by ShoiraTa** [comment]
# Status: Approved :heavy_check_mark::heavy_check_mark: :heavy_check_mark: 
Hi @blessedjasonmwanza ,
Congratulations :tada: Thank you for implementing changes suggested previously :pray:
### Happy Coding :clap: :clap: :clap:

**Pull request merged**
